### ISSUE TITLE
-resample-iso raises the exception Unknown command 

### ISSUE THREAD

**Issue by MehdiShekarnabi** [pyushkevich/c3d#7]
Hi, I was trying resampling options, it seems that c3d -resample-iso always raises the following exception:
Unknown command -resample-iso
Unknown exception caught by convert3d
  When processing command: -resample-iso
Just wanted to report that
Bests

**Comment by crossmanith** [comment]
I can't reproduce this error. Which version do you use (c3d -version)? Do you provide parameter min|max? Without this I also get an exception.

**Comment by br-cpvc** [comment]
@MehdiShekarnabi is this still a problem? If so, could you describe it a little deeper, maybe I can help.

**Comment by pyushkevich** [comment]
I think it may have been an issue of using an older version.

**Comment by br-cpvc** [comment]
@pyushkevich Ok, super. Thanks for the reply. Maybe the issue should be close then. The user can always open a new issue or reopen this one with more information if he needs further help.

**Comment by MehdiShekarnabi** [comment]
Sorry for my late response. I no longer use this application and do not
know if the problem is fixed or not.
Thank you for your follow up.
Have a nice day
Mehdi
